  CHECKER_FAILED = 0,
  RUNNER_FAILED = 1,
  BALANCE_TRANSFER_FAILED, 2
  EXECUTE_CMD_FAILED, 3 
  EXECUTE_CMD_TIMEOUT,4
  NO_GAS_REMAINING_FOUND, 5 
  NO_ACCEPTED_FOUND, 6
  CALL_CONTRACT_FAILED, 7
  CREATE_CONTRACT_FAILED, 8
  JSON_OUTPUT_CORRUPTED, 9
  CONTRACT_NOT_EXIST,
  STATE_CORRUPTED,
  LOG_ENTRY_INSTALL_FAILED,
  MESSAGE_CORRUPTED,
  RECEIPT_IS_NULL,
  MAX_DEPTH_REACHED,
  CHAIN_CALL_DIFF_SHARD,
  PREPARATION_FAILED,
  NO_OUTPUT,
  OUTPUT_ILLEGAL