export default [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'sender', type: 'address'},
      {indexed: true, internalType: 'address', name: 'signer', type: 'address'},
      {indexed: true, internalType: 'bytes4', name: 'funcSig', type: 'bytes4'},
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'digest',
        type: 'bytes32',
      },
    ],
    name: 'Relayed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'previousAdminRole',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'newAdminRole',
        type: 'bytes32',
      },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {indexed: true, internalType: 'address', name: 'sender', type: 'address'},
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {indexed: true, internalType: 'address', name: 'sender', type: 'address'},
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{internalType: 'bytes32', name: '', type: 'bytes32'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MINTER_ROLE',
    outputs: [{internalType: 'bytes32', name: '', type: 'bytes32'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NAME',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'VERSION',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'account', type: 'address'}],
    name: 'addMinter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address[]', name: 'accounts', type: 'address[]'}],
    name: 'addMinters',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
    ],
    name: 'claimTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
      {internalType: 'string[]', name: 'keys', type: 'string[]'},
      {internalType: 'string[]', name: 'values', type: 'string[]'},
    ],
    name: 'claimToWithRecords',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address payable', name: 'receiver', type: 'address'},
    ],
    name: 'closeMinter',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cnsMintingController',
    outputs: [
      {internalType: 'contract IMintingController', name: '', type: 'address'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cnsResolver',
    outputs: [{internalType: 'contract IResolver', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cnsURIPrefixController',
    outputs: [
      {
        internalType: 'contract IURIPrefixController',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'bytes32', name: 'role', type: 'bytes32'}],
    name: 'getRoleAdmin',
    outputs: [{internalType: 'bytes32', name: '', type: 'bytes32'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {internalType: 'address', name: 'account', type: 'address'},
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {internalType: 'address', name: 'account', type: 'address'},
    ],
    name: 'hasRole',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IUNSRegistry',
        name: 'unsRegistry_',
        type: 'address',
      },
      {
        internalType: 'contract IMintingController',
        name: 'cnsMintingController_',
        type: 'address',
      },
      {
        internalType: 'contract IURIPrefixController',
        name: 'cnsURIPrefixController_',
        type: 'address',
      },
      {
        internalType: 'contract IResolver',
        name: 'cnsResolver_',
        type: 'address',
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'account', type: 'address'}],
    name: 'isMinter',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
    ],
    name: 'mintSLD',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
      {internalType: 'string[]', name: 'keys', type: 'string[]'},
      {internalType: 'string[]', name: 'values', type: 'string[]'},
    ],
    name: 'mintSLDWithRecords',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'bytes', name: 'data', type: 'bytes'},
      {internalType: 'bytes', name: 'signature', type: 'bytes'},
    ],
    name: 'relay',
    outputs: [{internalType: 'bytes', name: '', type: 'bytes'}],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'account', type: 'address'}],
    name: 'removeMinter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address[]', name: 'accounts', type: 'address[]'}],
    name: 'removeMinters',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceMinter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {internalType: 'address', name: 'account', type: 'address'},
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'bytes32', name: 'role', type: 'bytes32'},
      {internalType: 'address', name: 'account', type: 'address'},
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address payable', name: 'receiver', type: 'address'},
    ],
    name: 'rotateMinter',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
    ],
    name: 'safeMintSLD',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
      {internalType: 'bytes', name: 'data', type: 'bytes'},
    ],
    name: 'safeMintSLD',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
      {internalType: 'string[]', name: 'keys', type: 'string[]'},
      {internalType: 'string[]', name: 'values', type: 'string[]'},
    ],
    name: 'safeMintSLDWithRecords',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tld', type: 'uint256'},
      {internalType: 'string', name: 'label', type: 'string'},
      {internalType: 'string[]', name: 'keys', type: 'string[]'},
      {internalType: 'string[]', name: 'values', type: 'string[]'},
      {internalType: 'bytes', name: 'data', type: 'bytes'},
    ],
    name: 'safeMintSLDWithRecords',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'resolver', type: 'address'}],
    name: 'setResolver',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'string', name: 'prefix', type: 'string'}],
    name: 'setTokenURIPrefix',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'bytes4', name: 'interfaceId', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unsRegistry',
    outputs: [
      {internalType: 'contract IUNSRegistry', name: '', type: 'address'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
