name: Release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"
          > ~/.npmrc

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn publish

      - name: Push version tag
        run: yarn release:tag
